import React from 'react';
import {
  MapPin,
  Navigation,
  Send,
  Users,
  Plus,
  Search,
  Bell,
  Flag,
  Mic,
  MicOff,
  Smile,
  ChevronLeft,
  ChevronRight,
  X,
  Share2,
  Receipt,
  Utensils,
  BedDouble,
  Car,
  Backpack,
  CornerDownLeft,
  ArrowDownLeft,
  ArrowUpRight,
  CircleCheckBig,
  Signal,
  Wifi,
  BatteryFull,
  MessageCircle,
  Map,
  User,
  Lock,
  Eye,
  EyeOff,
  LogOut,
  Settings,
  Home,
  Calendar,
  ListTodo,
  ShoppingCart,
  Image,
  Sparkles,
  History,
  PlusCircle,
  Circle,
  Trash2,
  Check,
  Camera,
  Pencil,
  Play,
  Pause,
  Wallet,
  Banknote,
  Shield,
  KeyRound,
  Copy,
  type LucideIcon,
} from 'lucide-react-native';

// FamilyChats uses Lucide (https://lucide.dev) as its icon set — rounded, 2px
// stroke, matching FamilyChats's friendly geometry. Substituted in the original
// design system because no brand icon set was provided. This registry
// covers every glyph referenced by the FamilyChats app screens.
const REGISTRY: Record<string, LucideIcon> = {
  'map-pin': MapPin,
  navigation: Navigation,
  send: Send,
  users: Users,
  plus: Plus,
  search: Search,
  bell: Bell,
  flag: Flag,
  mic: Mic,
  'mic-off': MicOff,
  smile: Smile,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  x: X,
  'share-2': Share2,
  receipt: Receipt,
  utensils: Utensils,
  'bed-double': BedDouble,
  car: Car,
  backpack: Backpack,
  'corner-down-left': CornerDownLeft,
  'arrow-down-left': ArrowDownLeft,
  'arrow-up-right': ArrowUpRight,
  'check-circle-2': CircleCheckBig,
  signal: Signal,
  wifi: Wifi,
  'battery-full': BatteryFull,
  'message-circle': MessageCircle,
  map: Map,
  user: User,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  'log-out': LogOut,
  settings: Settings,
  home: Home,
  calendar: Calendar,
  'list-todo': ListTodo,
  'shopping-cart': ShoppingCart,
  image: Image,
  sparkles: Sparkles,
  history: History,
  'plus-circle': PlusCircle,
  circle: Circle,
  trash: Trash2,
  check: Check,
  camera: Camera,
  pencil: Pencil,
  play: Play,
  pause: Pause,
  wallet: Wallet,
  banknote: Banknote,
  shield: Shield,
  key: KeyRound,
  copy: Copy,
};

export type IconName = keyof typeof REGISTRY;

export interface IconProps {
  name: string;
  size?: number;
  strokeWidth?: number;
  color?: string;
}

/** FamilyChats Icon — thin wrapper over Lucide, the brand's icon set. */
export function Icon({ name, size = 20, strokeWidth = 2, color = '#443C34' }: IconProps) {
  const Glyph = REGISTRY[name];
  if (!Glyph) return null;
  return <Glyph size={size} strokeWidth={strokeWidth} color={color} />;
}
